package it.polimi.ingsw.model;

public enum TurnState {
    BEFORESTART,
    PREPARATION,
    CHOOSELEADERCARDS,
    CHOOSERESOURCES,
    ENDPREPARATION,
    START,
    MARKETPHASE,
    WHITEMARBLES,
    CHOICE,
    ORGANIZERESOURCES,
    MANAGERESOURCES,
    ADDRESOURCES,
    BUYDEVELOPMENTCARDPHASE,
    PAYDEVELOPMENTCARD,
    PRODUCTIONPHASE,
    PAYPRODUCTIONS,
    ENDTURN
}
