package it.polimi.ingsw.client;

public enum TypeOfCommand {
    FOLD,
    NICKNAME,

    SELECTMARKETPHASE,
    STARTMARKETPHASE,
    WHITEMARBLES,
    SELECTBUYDEVELOPMENTCARDPHASE,
    ORGANIZERESOURCES,
    SETSTORAGETYPES,
    MANAGERESOURCESBYDEFAULT,
    MANAGERESOURCES,
    STARTADDRESOURCES,
    ADDRESOURCES,
    DISCARDRESOURCES,

    PAYCARDFROMCHEST, PAYCARDFROMSTORAGE, SELECTPRODUCTIONPHASE, ACTIVATEPERSONALPRODUCTION, ACTIVATEPRODUCTION, ACTIVATESPECIALPRODUCTION, STARTPAYPRODUCTION, PAYPRODUCTIONFROMCHEST, PAYPRODUCTIONFROMSTORAGE, BUYDEVELOPMENTCARD


}
