package it.polimi.ingsw.client;

public enum TypeOfCommand {
    FOLD,

    QUICKSTART,
    NEWMATCH,
    REJOIN,

    NICKNAME,
    DRAWLEADERCARDS,
    DISCARDLEADERCARDS,
    SETINITSTORAGETYPES,
    ADDINITRESOURCES,

    VIEWMARKET, VIEWLEADERS, VIEWFAITHTRACK, VIEWDEVELOPMENTCARDSTOBUY, VIEWPRODUCTIONS, VIEWRESOURCES,
    VIEWOTHERPLAYERS, VIEWOTHERPLAYERNUMBER,

    SELECTMARKETPHASE,
    STARTMARKETPHASE,
    WHITEMARBLES,
    SELECTBUYDEVELOPMENTCARDPHASE,
    ORGANIZERESOURCES,
    SETSTORAGETYPES,
    MANAGERESOURCESBYDEFAULT,
    MANAGERESOURCES,
    STARTADDRESOURCES,
    ADDRESOURCES,
    DISCARDRESOURCES,

    PAYCARDFROMCHEST, PAYCARDFROMSTORAGE, SELECTPRODUCTIONPHASE, ACTIVATEPERSONALPRODUCTION, ACTIVATEPRODUCTION, ACTIVATESPECIALPRODUCTION, STARTPAYPRODUCTION, PAYPRODUCTIONFROMCHEST, PAYPRODUCTIONFROMSTORAGE, BUYDEVELOPMENTCARD,

    ACTIVATELEADERCARD,
    DISCARDLEADERCARD,
    REORGANIZERESOURCES,
    VIEWDEVELOPMENTCARD,
    ENDTURN;
}
