package it.polimi.ingsw.client;

public enum TypeOfCommand {
    FOLD,
    NICKNAME,
    SELECTMARKETPHASE,
    STARTMARKETPHASE,
    WHITEMARBLES,
    SELECTBUYDEVELOPMENTCARDPHASE,
    ORGANIZERESOURCES,
    PAYCARDFROMCHEST, PAYCARDFROMSTORAGE, SELECTPRODUCTIONPHASE, ACTIVATEPERSONALPRODUCTION, ACTIVATEPRODUCTION, ACTIVATESPECIALPRODUCTION, STARTPAYPRODUCTION, PAYPRODUCTIONFROMCHEST, PAYPRODUCTIONFROMSTORAGE, BUYDEVELOPMENTCARD


}
